"""
I/O catalog for Phase 3, Phase 4a, Phase 4 insertion, and Phase 4 hyperdoc writing.

Generated by reading every .py file (excluding __init__.py) in:
  - phase_3_hyperdoc_writing/ (including evidence/ subdir)
  - phase_4a_aggregation/
  - phase_4_insertion/
  - phase_4_hyperdoc_writing/

For each file: reads, writes, and imports_from (pipeline module imports).
"""

PHASE3_4_IO = {
    # =========================================================================
    # phase_3_hyperdoc_writing/
    # =========================================================================
    "phase_3_hyperdoc_writing/collect_file_evidence.py": {
        "reads": [
            "session_metadata.json",
            "geological_notes.json",
            "semantic_primitives.json",
            "explorer_notes.json",
            "file_genealogy.json",
            "thread_extractions.json",
            "idea_graph.json",
            "grounded_markers.json",
            "synthesis.json",
            "claude_md_analysis.json",
            "file_dossiers.json",
        ],
        "writes": [
            "output/session_{sid}/file_evidence/{safe_filename}_evidence.json",
        ],
        "imports_from": ["tools.json_io", "tools.log_config"],
    },
    "phase_3_hyperdoc_writing/write_hyperdocs.py": {
        "reads": [
            "phase_3_hyperdoc_writing/file_dossiers.json",
            "phase_3_hyperdoc_writing/grounded_markers.json",
            "phase_3_hyperdoc_writing/idea_graph.json",
            "phase_3_hyperdoc_writing/claude_md_analysis.json",
        ],
        "writes": [
            "phase_3_hyperdoc_writing/hyperdoc_blocks/{filename_stem}_hyperdoc.txt",
        ],
        "imports_from": ["tools.json_io", "tools.log_config"],
    },
    "phase_3_hyperdoc_writing/generate_viewer.py": {
        "reads": [
            "session_metadata.json",
            "thread_extractions.json",
            "geological_notes.json",
            "semantic_primitives.json",
            "explorer_notes.json",
            "idea_graph.json",
            "synthesis.json",
            "grounded_markers.json",
            "file_dossiers.json",
            "claude_md_analysis.json",
            "hyperdoc_blocks/*_hyperdoc.txt",  # load_text() reads from hyperdoc_blocks/
        ],
        "writes": [
            "{BASE}/pipeline_viewer.html",
        ],
        "imports_from": ["config", "tools.log_config"],
    },
    "phase_3_hyperdoc_writing/write_more_hyperdocs.py": {
        "reads": [
            "{BASE}/file_dossiers.json",
            "{BASE}/grounded_markers.json",
            "{V5}/{filename}.py",  # source code files for insertion
        ],
        "writes": [
            "{BASE}/hyperdoc_blocks/{filename_stem}_hyperdoc.txt",
            "{BASE}/hyperdoc_previews/{filename}.py",
            "{BASE}/hyperdoc_code_files/{filename}.py",
        ],
        "imports_from": ["config", "tools.log_config"],
    },
    "phase_3_hyperdoc_writing/evidence_resolver.py": {
        "reads": [],  # Pure logic; reads are delegated to evidence renderer instances
        "writes": [],  # Pure logic; returns resolved text strings
        "imports_from": [
            "phase_3_hyperdoc_writing.evidence",
            "tools.log_config",
        ],
    },
    "phase_3_hyperdoc_writing/generate_dossiers.py": {
        "reads": [
            "session_metadata.json",
            "grounded_markers.json",
            "idea_graph.json",
            "thread_extractions.json",
            "file_dossiers.json",       # re-reads for verification pass
            "claude_md_analysis.json",   # re-reads for verification pass
        ],
        "writes": [
            "file_dossiers.json",
            "claude_md_analysis.json",
        ],
        "imports_from": ["tools.json_io", "tools.log_config"],
    },
    # =========================================================================
    # phase_3_hyperdoc_writing/evidence/  (renderer submodules)
    # =========================================================================
    "phase_3_hyperdoc_writing/evidence/base.py": {
        "reads": [
            # Lazy-loaded via properties from session search dirs:
            "enriched_session.json",
            "semantic_primitives.json",
            "idea_graph.json",
            "thread_extractions.json",
            "geological_notes.json",
            "grounded_markers.json",
            "file_dossiers.json",
        ],
        "writes": [],  # Base class; does not write files
        "imports_from": ["tools.json_io", "tools.log_config"],
    },
    "phase_3_hyperdoc_writing/evidence/debug_sequence.py": {
        "reads": [],  # Inherits reads from base.EvidenceRenderer (enriched_session.json, semantic_primitives.json)
        "writes": [],  # Returns rendered string
        "imports_from": ["phase_3_hyperdoc_writing.evidence.base"],
    },
    "phase_3_hyperdoc_writing/evidence/emotional_arc.py": {
        "reads": [],  # Inherits reads from base.EvidenceRenderer (semantic_primitives.json)
        "writes": [],  # Returns rendered string
        "imports_from": ["phase_3_hyperdoc_writing.evidence.base"],
    },
    "phase_3_hyperdoc_writing/evidence/idea_transition.py": {
        "reads": [],  # Inherits reads from base.EvidenceRenderer (idea_graph.json)
        "writes": [],  # Returns rendered string
        "imports_from": ["phase_3_hyperdoc_writing.evidence.base"],
    },
    "phase_3_hyperdoc_writing/evidence/reaction_log.py": {
        "reads": [],  # Inherits reads from base.EvidenceRenderer (thread_extractions.json, enriched_session.json)
        "writes": [],  # Returns rendered string
        "imports_from": ["phase_3_hyperdoc_writing.evidence.base"],
    },
    "phase_3_hyperdoc_writing/evidence/file_timeline.py": {
        "reads": [
            "file_evidence/{safe_filename}_evidence.json",  # Pre-computed evidence files
        ],  # Also inherits reads from base.EvidenceRenderer (thread_extractions.json, enriched_session.json)
        "writes": [],  # Returns rendered string
        "imports_from": ["phase_3_hyperdoc_writing.evidence.base"],
    },
    "phase_3_hyperdoc_writing/evidence/geological_event.py": {
        "reads": [],  # Inherits reads from base.EvidenceRenderer (geological_notes.json, enriched_session.json, semantic_primitives.json)
        "writes": [],  # Returns rendered string
        "imports_from": ["phase_3_hyperdoc_writing.evidence.base"],
    },
    "phase_3_hyperdoc_writing/evidence/decision_trace.py": {
        "reads": [],  # Inherits reads from base.EvidenceRenderer (grounded_markers.json, idea_graph.json)
        "writes": [],  # Returns rendered string
        "imports_from": ["phase_3_hyperdoc_writing.evidence.base"],
    },
    # =========================================================================
    # phase_4a_aggregation/
    # =========================================================================
    "phase_4a_aggregation/aggregate_dossiers.py": {
        "reads": [
            "output/session_*/file_dossiers.json",                    # all session dossiers
            "output/code_similarity_index.json",                      # or ~/PERMANENT_HYPERDOCS/indexes/code_similarity_index.json
            "output/session_*/file_genealogy.json",                   # per-session genealogy
            "~/PERMANENT_HYPERDOCS/sessions/session_*/file_genealogy.json",
            "output/session_*/session_metadata.json",                 # for frustration peaks
            "output/session_*/enriched_session.json",                 # for file mentions near frustration peaks
            "output/session_*/enriched_session_v2.json",              # preferred v2 enriched session
            "output/session_*/file_evidence/*_evidence.json",         # Phase 3a cross-session evidence
            "~/PERMANENT_HYPERDOCS/sessions/session_*/file_evidence/*_evidence.json",
        ],
        "writes": [
            "output/cross_session_file_index.json",
            "output/hyperdoc_inputs/{safe_filename}.json",            # per-file extracts (3+ sessions)
            "~/PERMANENT_HYPERDOCS/hyperdoc_inputs/{safe_filename}.json",
        ],
        "imports_from": ["tools.log_config", "tools.file_lock"],
    },
    # =========================================================================
    # phase_4_insertion/
    # =========================================================================
    "phase_4_insertion/insert_hyperdocs_v2.py": {
        "reads": [
            "{V5_CODE}/{filename}.py",               # source code files
            "{BASE}/hyperdoc_v2/{filename}_header.txt",
            "{BASE}/hyperdoc_v2/{filename}_inline.json",
            "{BASE}/hyperdoc_v2/{filename}_footer.txt",
        ],
        "writes": [
            "{BASE}/hyperdoc_previews_v2/{filename}.py",
        ],
        "imports_from": ["config"],
    },
    "phase_4_insertion/insert_hyperdocs.py": {
        "reads": [
            "{V5_CODE}/{source_file}.py",            # source code files
            "{BASE}/hyperdoc_blocks/{block_file}_hyperdoc.txt",
        ],
        "writes": [
            "{BASE}/hyperdoc_previews/{source_file}.py",
        ],
        "imports_from": ["config"],
    },
    "phase_4_insertion/hyperdoc_layers.py": {
        "reads": [
            "~/PERMANENT_HYPERDOCS/hyperdocs/{stem}_hyperdoc.json",  # existing hyperdocs
            "~/PERMANENT_HYPERDOCS/hyperdocs/*_hyperdoc.json",       # --stats and --migrate glob
        ],
        "writes": [
            "~/PERMANENT_HYPERDOCS/hyperdocs/{stem}_hyperdoc.json",  # save/append/migrate
        ],
        "imports_from": ["config"],
    },
    "phase_4_insertion/insert_from_phase4b.py": {
        "reads": [
            "output/hyperdocs/*_hyperdoc.json",                      # all hyperdoc JSONs
            # Source files found via find_source_file() searching:
            # ~/*, ~/.claude/hooks/*, apps/**/*, archive/**/*, output/**/*
            "{source_file}.py",
            "{source_file}.md",
            "{source_file}.html",
            "{source_file}.js",
            "{source_file}.json",
            "{source_file}.toml",
            "{source_file}.txt",
        ],
        "writes": [
            "output/enhanced_files_archive/{filename}.py",
            "output/enhanced_files_archive/{parent}__{filename}.py",
            "output/enhanced_files_archive/{filename}.md",
            "output/enhanced_files_archive/{filename}.html",
            "output/enhanced_files_archive/{filename}.json.hyperdoc.md",
        ],
        "imports_from": [],
    },
    # =========================================================================
    # phase_4_hyperdoc_writing/
    # =========================================================================
}
